<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use App\Services\GoogleMeetService;
use App\Models\Meeting;
use Carbon\Carbon;

class AutoGenerateDailyMeetings extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'meetings:auto-generate';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Automatically generate daily meetings for the next 7 days';

    protected $googleMeetService;

    public function __construct(GoogleMeetService $googleMeetService)
    {
        parent::__construct();
        $this->googleMeetService = $googleMeetService;
    }

    /**
     * Execute the console command.
     */
    public function handle()
    {
        $this->info('🚀 Starting automatic daily meeting generation...');

        $generated = 0;
        $skipped = 0;

        // Generate meetings for the next 7 days
        for ($i = 0; $i < 7; $i++) {
            $date = Carbon::now()->addDays($i);

            // Check if meeting already exists for this date
            $existingMeeting = Meeting::where('date', $date->format('Y-m-d'))->first();

            if ($existingMeeting) {
                $this->line("⏭️  Meeting already exists for {$date->format('M d, Y')}");
                $skipped++;
                continue;
            }

            try {
                // Generate meeting for this date
                $meeting = $this->googleMeetService->createDailyMeet($date);

                $this->line("✅ Generated meeting for {$date->format('M d, Y')}");
                $this->line("   📅 Title: {$meeting->title}");
                $this->line("   🔗 Link: {$meeting->meet_link}");

                $generated++;

            } catch (\Exception $e) {
                $this->error("❌ Failed to generate meeting for {$date->format('M d, Y')}: " . $e->getMessage());
            }
        }

        $this->info("📊 Summary:");
        $this->line("   Generated: {$generated} meetings");
        $this->line("   Skipped: {$skipped} meetings (already exist)");

        if ($generated > 0) {
            $this->info("🎉 Automatic meeting generation completed successfully!");
        } else {
            $this->info("ℹ️  All meetings already exist for the next 7 days.");
        }

        return Command::SUCCESS;
    }
}
