<?php

namespace Database\Seeders;

use App\Models\AgentClientAssignment;
use App\Models\User;
use App\Models\WorkUpdate;
use Carbon\Carbon;
use Carbon\CarbonPeriod;
use Illuminate\Database\Seeder;

class ClientWorkUpdatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $clients = User::where('role_id', User::ROLE_CLIENT)->orderBy('id')->get();
        $agents = User::where('role_id', User::ROLE_AGENT)->orderBy('id')->get()->keyBy('id');
        $admin = User::whereIn('role_id', [User::ROLE_SUPER_ADMIN, User::ROLE_ADMIN])->orderBy('id')->first();

        if ($clients->isEmpty() || $agents->isEmpty()) {
            $this->command?->warn('Client work update seeder skipped because no clients or agents were found.');
            return;
        }

        $pairings = AgentClientAssignment::query()
            ->orderByDesc('is_active')
            ->orderBy('assigned_date')
            ->get()
            ->groupBy('client_id')
            ->map(function ($assignments) {
                return $assignments->first();
            });

        $fallbackAgent = $agents->first();

        $jobTitles = [
            'Customer Support Specialist',
            'Operations Coordinator',
            'Virtual Assistant',
            'Sales Support Associate',
            'Executive Assistant',
            'Client Success Associate',
            'Data Entry Specialist',
            'Recruiting Coordinator',
        ];

        $companies = [
            'Northstar Solutions',
            'Summit Peak Digital',
            'Maple Ridge Partners',
            'Harborline Logistics',
            'Brightwell Systems',
            'Pioneer Global Services',
            'Evercrest Ventures',
            'Crestmark Consulting',
        ];

        $methods = [
            WorkUpdate::METHOD_WEB,
            WorkUpdate::METHOD_LINKEDIN,
            WorkUpdate::METHOD_EMAIL,
            WorkUpdate::METHOD_REFERRAL,
            WorkUpdate::METHOD_DIRECT,
        ];

        $applicationStatuses = [
            WorkUpdate::APPLICATION_STATUS_APPLIED,
            WorkUpdate::APPLICATION_STATUS_INTERVIEW,
            WorkUpdate::APPLICATION_STATUS_APPLIED,
            WorkUpdate::APPLICATION_STATUS_HIRED,
            WorkUpdate::APPLICATION_STATUS_APPLIED,
            WorkUpdate::APPLICATION_STATUS_REJECTED,
        ];

        $startDate = Carbon::create(2025, 12, 1)->startOfDay();
        $endDate = now()->startOfDay();

        if ($endDate->lt($startDate)) {
            $this->command?->warn('Client work update seeder skipped because the current date is before December 1, 2025.');
            return;
        }

        $createdCount = 0;

        foreach ($clients as $clientIndex => $client) {
            $pairing = $pairings->get($client->id);
            $agent = $pairing && isset($agents[$pairing->agent_id])
                ? $agents[$pairing->agent_id]
                : $fallbackAgent;

            if (! $agent) {
                continue;
            }

            foreach (CarbonPeriod::create($startDate, $endDate) as $date) {
                $daySeed = $clientIndex + $date->dayOfYear;
                $appliedAt = $date->copy()->setTime(9 + ($daySeed % 7), 15 + ($daySeed % 35), 0);
                $jobTitle = $jobTitles[$daySeed % count($jobTitles)];
                $company = $companies[$daySeed % count($companies)];
                $method = $methods[$daySeed % count($methods)];
                $applicationStatus = $applicationStatuses[$daySeed % count($applicationStatuses)];

                $workUpdate = WorkUpdate::query()->firstOrCreate(
                    [
                        'agent_id' => $agent->id,
                        'client_id' => $client->id,
                        'applied_date' => $date->toDateString(),
                    ],
                    [
                        'job_title' => $jobTitle,
                        'company' => $company,
                        'job_link' => 'https://example.com/jobs/' . $client->id . '-' . $date->format('Ymd'),
                        'job_success_link' => $applicationStatus === WorkUpdate::APPLICATION_STATUS_HIRED
                            ? 'https://example.com/success/' . $client->id . '-' . $date->format('Ymd')
                            : null,
                        'applied_method' => $method,
                        'application_status' => $applicationStatus,
                        'note' => 'Seeded daily client work update for dashboard testing and filtered export validation.',
                        'remarks' => 'Auto-generated by ClientWorkUpdatesSeeder.',
                        'status' => WorkUpdate::STATUS_APPROVED,
                        'approved_by' => $admin?->id,
                        'approved_at' => $appliedAt->copy()->addHour(),
                        'service_end_date' => $pairing?->service_end_date,
                        'created_at' => $appliedAt,
                        'updated_at' => $appliedAt,
                    ]
                );

                if ($workUpdate->wasRecentlyCreated) {
                    $createdCount++;
                }
            }
        }

        $this->command?->info("Client daily work updates seeded successfully. Created {$createdCount} new records.");
    }
}
